services:
  - type: web
    name: mediavault-backend
    runtime: docker
    dockerfilePath: ./docker/Dockerfile.backend
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DB_HOST
        value: db.wavokgzprgqhytcqxuic.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: "#L3g0M3n2oo2!-#Chr1st0ph3r!"
      - key: PYTHON_PATH
        value: python3
      - key: DOWNLOAD_PATH
        value: /var/www/backend/storage/downloads
      - key: APP_ENV
        value: production
