// =============================================================================
// MEDIAVAULT — SHARED TYPE DEFINITIONS
// =============================================================================
// This file is the single source of truth for every data shape in the app.
// Import from here with:  import type { MediaItem, Download } from '@/types'
// =============================================================================


// -----------------------------------------------------------------------------
// PLATFORM
// A "union type" — Platform can ONLY be one of these exact string values.
// WHY: If you accidentally write "Faceboook" (typo) TypeScript will show an
//      error immediately instead of silently passing a wrong value.
// -----------------------------------------------------------------------------
export type Platform =
  | 'facebook'
  | 'twitter'    // also known as X
  | 'instagram'
  | 'tiktok'
  | 'snapchat'
  | 'unknown'    // used when we cannot detect the platform from the URL


// -----------------------------------------------------------------------------
// MEDIA TYPE
// What kind of content a MediaItem is.
// -----------------------------------------------------------------------------
export type MediaType =
  | 'image'
  | 'video'
  | 'reel'     // short-form vertical video (Instagram Reel, TikTok)
  | 'story'    // disappearing 24h content
  | 'audio'
  | 'unknown'


// -----------------------------------------------------------------------------
// DOWNLOAD STATUS
// The lifecycle of a single download job.
//   pending   → queued but not started yet
//   active    → currently downloading (bytes flowing)
//   paused    → user hit pause; can be resumed
//   completed → file is fully saved to disk
//   failed    → an error occurred; can be retried
// -----------------------------------------------------------------------------
export type DownloadStatus =
  | 'pending'
  | 'active'
  | 'paused'
  | 'completed'
  | 'failed'


// -----------------------------------------------------------------------------
// MEDIA ITEM
// Represents a single photo, video, or reel found from a URL.
// This is what the Python extractor returns and what we display in the UI grid.
// -----------------------------------------------------------------------------
export interface MediaItem {
  // A unique ID generated by the backend (e.g. "fb_123456789").
  id: string

  // The original public URL the user pasted.
  sourceUrl: string

  // The actual direct URL to the media file (mp4, jpg, etc.).
  // This is what yt-dlp finds inside the post page.
  mediaUrl: string

  // Which social platform this came from.
  platform: Platform

  // Whether this is a photo, video, story, etc.
  mediaType: MediaType

  // Optional: the thumbnail image URL shown in the grid before the full file downloads.
  thumbnailUrl?: string

  // Optional: the username/handle of the account that posted this.
  username?: string

  // Optional: text caption accompanying the post.
  caption?: string

  // The file size in bytes. Optional because we may not know it before downloading.
  fileSizeBytes?: number

  // The duration in seconds for videos. Not applicable to images.
  durationSeconds?: number

  // The width and height of the media in pixels.
  width?: number
  height?: number

  // When the post was published (ISO 8601 string like "2024-06-19T10:30:00Z").
  postedAt?: string

  // When we extracted/discovered this item (set by the backend).
  extractedAt: string
}


// -----------------------------------------------------------------------------
// DOWNLOAD JOB
// Represents a download task in the Download Manager.
// One DownloadJob can contain multiple MediaItems (e.g. a carousel post).
// -----------------------------------------------------------------------------
export interface DownloadJob {
  // Unique ID for this download job (generated by the backend or frontend).
  id: string

  // The URL the user originally pasted (could be a post or a profile URL).
  sourceUrl: string

  // Which platform.
  platform: Platform

  // All the media items found inside this URL.
  items: MediaItem[]

  // The current state of the overall job.
  status: DownloadStatus

  // Progress from 0 to 100. Calculated as: (downloadedBytes / totalBytes) * 100.
  progressPercent: number

  // How many bytes have been received so far.
  downloadedBytes: number

  // Total size of all files in this job. May be 0 if unknown.
  totalBytes: number

  // Download speed in bytes per second (used to show "2.5 MB/s" in the UI).
  speedBytesPerSec: number

  // Estimated time remaining in seconds.
  etaSeconds: number

  // The folder on disk where files will be saved.
  destinationPath: string

  // Error message to display if status === 'failed'.
  errorMessage?: string

  // How many times this job has been retried after failure.
  retryCount: number

  // When the user started this download (ISO 8601).
  createdAt: string

  // When the download finished (ISO 8601). Only set when status === 'completed'.
  completedAt?: string
}


// -----------------------------------------------------------------------------
// PROFILE SCAN RESULT
// When a user scans a profile URL, the backend returns this object.
// It contains the account info and a list of all public MediaItems found.
// -----------------------------------------------------------------------------
export interface ProfileScanResult {
  // The profile URL the user submitted.
  profileUrl: string

  // Which platform.
  platform: Platform

  // The account's username (e.g. "nasa").
  username: string

  // The display name shown on the profile (e.g. "NASA").
  displayName?: string

  // URL to the account's profile picture.
  avatarUrl?: string

  // Total number of posts found on the public profile.
  totalPostsFound: number

  // All the individual media items found across all posts.
  // For large profiles this could be hundreds of items.
  items: MediaItem[]

  // When we finished scanning the profile.
  scannedAt: string
}


// -----------------------------------------------------------------------------
// DOWNLOAD HISTORY RECORD
// Stored in MySQL after a download completes.
// Used to show the history page and detect duplicates.
// -----------------------------------------------------------------------------
export interface HistoryRecord {
  // Auto-incremented primary key from the MySQL downloads table.
  id: number

  // The original URL.
  sourceUrl: string

  // Which platform.
  platform: Platform

  // Full path to the saved file on disk.
  filePath: string

  // File size in bytes.
  fileSizeBytes: number

  // The media type that was downloaded.
  mediaType: MediaType

  // SHA-256 hash of the file content — used to detect duplicates.
  fileHash: string

  // When the download was saved to history.
  downloadedAt: string
}


// -----------------------------------------------------------------------------
// APP SETTINGS
// User preferences stored in localStorage (and optionally in the database).
// -----------------------------------------------------------------------------
export interface AppSettings {
  // 'light' | 'dark' | 'system' — the user's preferred color scheme.
  theme: 'light' | 'dark' | 'system'

  // Default folder where all downloads go.
  downloadPath: string

  // Whether to automatically create sub-folders per platform and username.
  // e.g.  downloads/instagram/nasa/2024-06-19_post-id.mp4
  autoOrganize: boolean

  // Whether to rename files with timestamps.
  timestampRename: boolean

  // Whether to skip files that already exist (duplicate detection).
  skipDuplicates: boolean

  // Maximum simultaneous downloads (1-10).
  maxConcurrentDownloads: number

  // Whether to show a desktop notification when a download finishes.
  notifyOnComplete: boolean
}


// -----------------------------------------------------------------------------
// API RESPONSE WRAPPER
// The PHP backend always returns JSON in this shape.
// "T" is a generic: it means "whatever type the data field holds".
// Example: ApiResponse<MediaItem[]> means data is an array of MediaItems.
// -----------------------------------------------------------------------------
export interface ApiResponse<T> {
  // true = the request succeeded, false = something went wrong.
  success: boolean

  // The actual payload. Only present when success === true.
  data?: T

  // Human-readable error message. Only present when success === false.
  message?: string

  // HTTP-style error code for programmatic handling (e.g. 404, 422, 500).
  code?: number
}


// -----------------------------------------------------------------------------
// FILTER OPTIONS
// Controls which media items are shown in the media grid.
// -----------------------------------------------------------------------------
export interface FilterOptions {
  // Filter by media type. Empty array = show all types.
  mediaTypes: MediaType[]

  // Filter by platform. Empty array = show all platforms.
  platforms: Platform[]

  // Only show items downloaded after this date (ISO 8601). null = no lower bound.
  dateFrom: string | null

  // Only show items downloaded before this date (ISO 8601). null = no upper bound.
  dateTo: string | null

  // Text to match against caption, username, or filename.
  searchQuery: string

  // Which field to sort by.
  sortBy: 'date' | 'size' | 'platform' | 'name'

  // Sort direction.
  sortDirection: 'asc' | 'desc'
}
